### ISSUE TITLE
IntersectionObserve polyfill is really slow

### ISSUE THREAD

**Issue by tfiwm** [thisissoon/angular-inviewport#31]
Hi i like this directive really a lot but intersection observer polyfill from w3c is really slow if you have multiple elements when you are using this technique.

It would be nice if this directive makes the use of the intersection observer optional. So it should have a build in feature detection which is quite small.

Than this directive still can be used and if there is no support just throw the event inViewportChange directly.

I will create a PR for this change and than you can think about it!

**Comment by tfiwm** [comment]
Open PR for that issue -> #32

**Comment by edoparearyee** [comment]
I've left a comment about this PR on #32  however. My initial thought is that possibly the actual intersection observer logic is not the issue but rather the logic in the callback that you have running.

Are you throttling the events from the directive so that any callbacks you are running do not run on each pixel scrolled?

See here for a `debounce` example: https://github.com/thisissoon/angular-inviewport#debounce-example

**Comment by tfiwm** [comment]
I tried it with disabling the Mutations on dom change but still really slow. I will try it with the debounceTime but i my tests i even disabled the observe in afterInit and it was really slow ... so even without subscribing. You can really easy test it with the example in my PR.
Activate polyfill and take a look how slow it is :)

**Comment by tfiwm** [comment]
@edoparearyee I tried with the debounceTime and like expected no change. Just check the example and you see it is the polyfill which has just bad performance with multiple usage

**Comment by edoparearyee** [comment]
Sorry about the delay in responding to this issue. #32 has been merged. 

This should be available now in v4.2.0 `npm i @thisissoon/angular-inviewport@4.2.0`
