### ISSUE TITLE
Problems with elements inside elements with overflow.

### ISSUE THREAD

**Issue by paulordbm** [thisissoon/angular-inviewport#7]
Hi,

I love how clean this package is but when I tried to use it in my project I couldn't make it to work with elements inside scrollable divs (`overflow: auto` or `overflow: true`).

I've come up with a simple [plunker example](https://embed.plnkr.co/BtUk1HxmVaTrlKbA0x24/) to reproduce the issue. It's based on your demo, but you can also watch the console for logs.

Basically the directive fails to recognize if the element is in or outside of the viewport.

Am I doing something wrong here or is this really a missing feature/bug?

Thanks in advance!

**Comment by edoparearyee** [comment]
Hi @paulordbm I think the issue is that currently the directive is only updated on window scroll events. When the directive is in another scrollable element the directive has no knowledge of this elements scroll events.

I think a solution would be to be able to specify an element which the directive will listen to it's scroll events and fallback to window if no element is specified. 

Thanks for reporting this, will look into it

**Comment by edoparearyee** [comment]
@paulordbm this should be resolved now. I'm hoping this will cover this use case. You can see an example of it being implemented in the readme [here](https://github.com/thisissoon/angular-inviewport#specify-parent-scrollable-element) or in the [demo](https://github.com/thisissoon/angular-inviewport/tree/master/src/demo)

**Comment by paulordbm** [comment]
@edoparearyee thanks very much for this. It works like a charm.
